### ISSUE TITLE
配置中的 sizeLimit 和 maxLogSize 单位不一致

### ISSUE THREAD

**Issue by nekolsd** [WJQSERVER-STUDIO/ghproxy#10]
版本 1.6.0 的配置中 server.sizeLimit 的单位为 Bytes，而 log.maxLogSize 的单位为 MB。建议统一修改为 MB 以防止混淆。

**Comment by WJQSERVER** [comment]
已进行相关修改,会随其他修改一并提交

**Comment by satomitoka** [comment]
團隊已進行相關修改，呢項更改預計會隨住下個測試版發佈

**Comment by WJQSERVER** [comment]
此修改已于24w19a与24w19b内实现,将会合入v1.6.1更新内,感谢您对本项目的建议！

**Comment by WJQSERVER** [comment]
我们已将此补丁并入[v1.6.1](https://github.com/WJQSERVER-STUDIO/ghproxy/releases/tag/1.6.1)，故关闭此ISSUE,在此感谢您提出了此问题
