### ISSUE TITLE
似乎不支持 gist?

### ISSUE THREAD

**Issue by JohnsonRan** [WJQSERVER-STUDIO/ghproxy#11]
访问gist链接为空白🤔

**Comment by WJQSERVER** [comment]
我们需要更加详细的信息,能否提交日志与截图

**Comment by JohnsonRan** [comment]
Docker搭建的 后端报错
```
[WARNING] Invalid URL: https://gist.githubusercontent.com/JohnsonRan/ce7317916a729522d2f78d9264c539bf/raw/PGP%!P(MISSING)ublic%!K(MISSING)ey
```
测试URL:
`https://gist.githubusercontent.com/JohnsonRan/ce7317916a729522d2f78d9264c539bf/raw/PGP%2520Public%2520Key`

**Comment by WJQSERVER** [comment]
已于24w19b中修复此问题

**Comment by JohnsonRan** [comment]
可以了，感谢！

**Comment by WJQSERVER** [comment]
感谢您提出了此问题,您协助我们改进了此问题,我们会尽快将此补丁合并至v1.6.1,多谢合作!

**Comment by WJQSERVER** [comment]
我们需要将此ISSUE保持开启,直到问题补丁正式并入v1.6.1

**Comment by WJQSERVER** [comment]
我们已将此补丁并入[v1.6.1](https://github.com/WJQSERVER-STUDIO/ghproxy/releases/tag/1.6.1)，故关闭此ISSUE,在此感谢您提出了此问题

**Comment by WJQSERVER** [comment]
相关: https://github.com/WJQSERVER-STUDIO/ghproxy/issues/64

已通过重构的匹配器解决
