### ISSUE TITLE
大佬，这个keyob平台部署失败。

### ISSUE THREAD

**Issue by ilxp** [WJQSERVER-STUDIO/ghproxy#15]
大佬，在keyob上部署失败。选择Web service，再选docker输入：wjqserver/ghproxy:latest  然后一路默认。健康检测不通过。默认端口是8000.我改成7210  也不行啊。
![1730536983208](https://github.com/user-attachments/assets/9dc80848-bb7d-4900-9ae2-a474cdde4fc6)

**Comment by WJQSERVER** [comment]
您好,能否详细描述您的需求

**Comment by satomitoka** [comment]
我哋需要提醒你，您使用咗錯誤嘅標籤，並且冇提供詳細嘅問題描述。請補充資訊。

**Comment by ilxp** [comment]
这里是错误日志：
![1730537203950(1)](https://github.com/user-attachments/assets/5634ddd8-cb2f-4bce-b14b-a5fa7614f5e2)

**Comment by WJQSERVER** [comment]
我们需要您的配置与本程序生成的日志，keyob日志并没有帮助

**Comment by WJQSERVER** [comment]
您在本项目的讨论群组内吗,在群组内，您能以更高效率与开发者对话

**Comment by ilxp** [comment]
不在啊。我加下

**Comment by WJQSERVER** [comment]
您好,我们已测试了keyob平台，部署一切正常

**Comment by WJQSERVER** [comment]
> 不在啊。我加下

我们建议您加入 https://t.me/ghproxy_go 群组以高效获取支持

**Comment by WJQSERVER** [comment]
This Issues Timeout. You may open it again
