### ISSUE TITLE
关于nocache优化建议

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [WJQSERVER-STUDIO/ghproxy#18]
建议nocache版本去掉前置caddy，直接自行反代后端

**Comment by WJQSERVER** [comment]
nocache版本将会进行基于性能考量的修改，我们会去除caddy，让高并发且拥有一定技术的用户自行配置相关策略
此改进预计与v.1.7.1同步发布

**Comment by WJQSERVER** [comment]
已于v1.7.1完成相关处置
