### ISSUE TITLE
Github HTTP验证问题

### ISSUE THREAD

**Issue by Yizelove** [WJQSERVER-STUDIO/ghproxy#21]
可否加个配置ssl证书功能？

不知为何，我用宝塔和1panel面板的反向代理都无法使用HTTP认证信息功能，一直鉴权失败

我只能将docker端口直接设置为80进行访问，但是无法使用https，所以在此请求添加个配置ssl证书的功能

**Comment by WJQSERVER** [comment]
您是指鉴权模块有问题吗

**Comment by Yizelove** [comment]
我是指Github的http认证功能
使用宝塔或者1panel面板反代项目后Github的http认证功能无法正常使用
比如https://user:password@test.com/Github.com/xxx/xxx
这个链接无法正常使用，把test.com直接替换为ip+项目端口才能正常使用http认证功能

**Comment by Yizelove** [comment]
因此我想直接设置项目端口为80和443，所以想请求增加一个配置ssl证书的功能

**Comment by WJQSERVER** [comment]
你使用的是哪个版本

**Comment by WJQSERVER** [comment]
nocache 还是 release

**Comment by Yizelove** [comment]
我使用的是这个命令：
docker run -p 80:80 -v ./ghproxy/log/run:/data/ghproxy/log -v ./ghproxy/log/caddy:/data/caddy/log -v ./ghproxy/config:/data/ghproxy/config  --restart always wjqserver/ghproxy
应该是release

**Comment by WJQSERVER** [comment]
这问题很奇怪,release内置了反向代理程序,是nginx系的问题?

**Comment by WJQSERVER** [comment]
您可以考虑对/data/caddy/Caddyfile进行修改,release版本内置了caddy

**Comment by Yizelove** [comment]
好的

**Comment by WJQSERVER** [comment]
您可以加入我们的讨论群组以获取更加即时的支持

**Comment by WJQSERVER** [comment]
使用内置caddy只需将`:80`配置块改为您的域名,并让caddy使用443端口,caddy会自动获取证书并自动化管理

**Comment by Yizelove** [comment]
> 使用内置caddy只需将`:80`配置块改为您的域名,并让caddy使用443端口,caddy会自动获取证书并自动化管理

请问该怎么修改呢？

**Comment by WJQSERVER** [comment]
夜色已深，能否明日在群组内详谈

**Comment by Yizelove** [comment]
好的，感谢你的解答

**Comment by WJQSERVER** [comment]
能否将您的经验贴出来，这会对其他用户带来一些便利，十分感谢

**Comment by WJQSERVER** [comment]
The issue seems to be resolved. If there are any further problems, please open the issue again.  
问题似乎已经解决，如果还有其他问题，请再次打开问题。
