### ISSUE TITLE
希望能够通过 Cloudflare Workers 部署 ghproxy

### ISSUE THREAD

**Issue by ZedWAreHK** [WJQSERVER-STUDIO/ghproxy#22]
### 功能描述

通过 Cloudflare Workers 部署 ghproxy。

### 功能原因

可以对于无服务器的用户部署 ghproxy。

### 功能实现

通过 Cloudflare Workers 部署 ghproxy，实现对 GitHub 资源的高效代理访问，降低国内用户访问 GitHub 资源的延迟和失败率。
github使用的是微软的CDN而不是使用cloudflare的cdn，不会造成cloudflare内部路由失败。因此按道理来说是可以通过 Cloudflare Workers 部署ghproxy的。并且还能够通过cloudflare cdn的anycast提高下载速度，这样就可以实现无服务器而且也没必要在经过服务器使延迟增加。

**Comment by WJQSERVER** [comment]
此项目完全基于go实现, 不考虑worker实现

**Comment by crazypeace** [comment]
这里有现成的项目

代码地址：https://github.com/crazypeace/gh-proxy

可以在这里进行测试运行：https://ghproxy.crazypeace.workers.dev/
