### ISSUE TITLE
[Features] ARM64 support

### ISSUE THREAD

**Issue by wang4386** [WJQSERVER-STUDIO/ghproxy#5]
目前docker镜像不支持arm

**Comment by WJQSERVER** [comment]
目前有计划支持arm64 linux
我们正在计划对docker镜像进行一些修改,你可以在PRE-RELEASES内看到,目前开发重心在计划将docker底包迁移至alpine
支持arm64 linux需要先对[WJQSERVER-STUDIO/golang-temp](https://github.com/WJQSERVER-STUDIO/golang-temp)模板库进行修改,再将开发规范同步至下属库,这是一个比较慢的过程,但已经在开发路线中
如果您有更好更快的方案,欢迎发起PR；如果没有,请稍安勿躁,等待主线开发
由此造成的不便我们十分抱歉,缺少开发者和时间与精力不足使我们不能面面俱到,敬请谅解

**Comment by WJQSERVER** [comment]
WJQSERVER-STUDIO(以下简称“我们”)在讨论意见后,认为此项支持需要对多个底层部件进行修改,我们首先需要修改WJQSERVER-
STUDIO/caddy,这是本项目的底包,然后修改WJQSERVER-STUDIO/golang-temp以统一开发规范，在经过若干测试版才能投入使用

---
由此造成的不便我们十分抱歉,缺少开发者和时间与精力不足使我们不能面面俱到,敬请谅解

**Comment by WJQSERVER** [comment]
能否对ARM64架构支持提供协助,我们需要测试此项目的底包WJQSERVER-STUDIO/caddy的ARM64支持,该支持目前无法验证,WJQSERVER-STUDIO团队目前没有可用的ARM64测试场景，若有望协助,请拉取`wjqserver/caddy:dev-test`镜像运行,注意tag必须是dev-test，返回caddy.log日志即可,我们无需搜集更多信息,若存在问题,请积极提出,谢谢

**Comment by WJQSERVER** [comment]
已于[v1.4.2](https://github.com/WJQSERVER-STUDIO/ghproxy/releases/tag/1.4.2)内初步实现

**Comment by WJQSERVER** [comment]
ARM64支持已并入主线,若您在v1.5.0前还未回复,我们将使用已完成标签关闭此ISSUE,感谢您的配合

**Comment by WJQSERVER** [comment]
v1.5.0已发布,我们将关闭此过时的ISSUE
